name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
     with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm test
    - run: npm run build --if-present
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - run: docker build . -t "revisionsystems/openjdk:16:latest" -t "revisionsystems/openjdk:$(cat jdk16/.version)"
    - run: docker build . -t "revisionsystems/openjdk:17:latest" -t "revisionsystems/openjdk:$(cat jdk17/.version)"
    - run: docker push "revisionsystems/openjdk"