name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: revisionsystems/ci-cd:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo test
