name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: revisionsystems/ci-cd

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo test
